required_version = "1.5.2"
error_on_line_overflow = true
error_on_unformatted = true
blank_lines_upper_bound = 0
# format_code_in_doc_comments = true
# format_strings = true
# hex_literal_case = "Lower"
# imports_layout = "Vertical"
max_width = 80
newline_style = "Unix"
# group_imports = "StdExternalCrate"
use_small_heuristics = "Max"
# wrap_comments = true
