# https://rust-lang.github.io/rustfmt
condense_wildcard_suffixes = true
doc_comment_code_block_width = 80
error_on_line_overflow = true
error_on_unformatted = true
fn_args_layout = "Vertical"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
# imports_granularity = "Module"
imports_layout = "Vertical"
max_width = 80
newline_style = "Unix"
normalize_doc_attributes = true
required_version = "1.5.1"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
